# Rubocop custom configuration
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - "bin/bundle"
    - "db/schema.rb"
    - "test/controllers/*"
  